package com.rusefi;

public class PinLine {

    private static final String PREFIX = "X1-";

    private static final int INDEX_FROM = 17;
    private static final int INDEX_TO = 32;

    private static final int Y_FROM = 215;

    private static final int X_FROM = 216;
    private static final int X_TO = 772;

    public static void main(String[] args) {

        int count = INDEX_TO - INDEX_FROM;
        float width = X_TO - X_FROM;
        float perPin = width / count;

        System.out.println("# auto-generated by PinLine.java");
        System.out.println("# " + INDEX_FROM + " " + INDEX_TO);
        System.out.println("# " + X_FROM + " " + X_TO);
        System.out.println("# " + Y_FROM);


        for (int i = INDEX_FROM; i <= INDEX_TO; i++) {

            int zeroIndex = i - INDEX_FROM;

            int x = (int) (X_FROM + zeroIndex * perPin);

            System.out.println("    - pin: " + PREFIX + i);
            System.out.println("      x: " + x);
            System.out.println("      y: " + Y_FROM);

            if (i % 10 == 0)
                System.out.println("\n");
        }
    }
}
