package com.rusefi;

import java.awt.*;
import java.awt.datatransfer.StringSelection;

public class PinLine {

    private static final String PREFIX = "";
    private static final String SUFFIX = "";

    private static final int INDEX_FROM = 49;
    private static final int INDEX_TO = 64;

    private static final int X_FROM = 216;
    private static final int X_TO = 772;

    private static final int Y_FROM = 215;

    public static void main(String[] args) {
        if (INDEX_FROM > INDEX_TO)
            throw new IllegalStateException("Indexing order " + INDEX_FROM + " to " + INDEX_TO);

        int count = INDEX_TO - INDEX_FROM;
        float width = X_TO - X_FROM;
        float perPin = width / count;

        StringBuffer header = new StringBuffer();

        header.append("# auto-generated by PinLine.java from can-log-tools\n");
        header.append("# " + INDEX_FROM + " " + INDEX_TO + "\n");
        header.append("# " + X_FROM + " " + X_TO + "\n");
        header.append("# " + Y_FROM + "\n");

        StringBuffer sb = new StringBuffer();

        for (int i = INDEX_FROM; i <= INDEX_TO; i++) {

            int zeroIndex = i - INDEX_FROM;

            int x = (int) (X_FROM + zeroIndex * perPin);

            sb.append("    - pin: " + PREFIX + i + SUFFIX + "\n");
            sb.append("      x: " + x + "\n");
            sb.append("      y: " + Y_FROM + "\n");

            if (i % 10 == 0)
                sb.append("\n");
        }


        StringSelection selection = new StringSelection(sb.toString());

        System.out.println("Setting clipboard content to:\n\n\n\n\n");
        System.out.println(sb);

        Toolkit.getDefaultToolkit().getSystemClipboard().setContents(selection, selection);
        System.out.println("\n\nhopefully it's in clipboard?");
    }
}
